disallowed-types = [
    # prefer hashbrown
    "std::collections::HashMap",
    "std::collections::HashSet",
]

disallowed-macros = [
    # only allowed in main.rs
    "std::print",
    "std::println",
    # use log crate instead
    "std::eprint",
    "std::eprintln",
]

disallowed-methods = [
    # run time of these methods scales linearly with the number of cores.
    "dashmap::DashMap::len",
    "dashmap::DashMap::iter",
    "dashmap::DashMap::clear",
]

type-complexity-threshold = 350
