[package]
name = "linear-algebra-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
lalrpop-util = { version = "0.22.2", features = [
    "lexer",
] }
egglog = { path = "../../" }

[build-dependencies]
lalrpop = "0.22.2"

[workspace]