name: Nightly Benchmark

on:
  schedule:
    - cron: '0 3 * * *'  # every night at 3 AM UTC
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  nightly-benchmark:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CARGO_INCREMENTAL=0" >> "$GITHUB_ENV"
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-codspeed
      - uses: Swatinem/rust-cache@v2
      - run: cargo codspeed build nightly_benchmarking -m walltime
      - uses: CodSpeedHQ/action@v3
        with:
          run: cargo codspeed run nightly_benchmarking -m walltime
